"""empty message

Revision ID: d816905a9506
Revises: 74245a210567
Create Date: 2023-01-24 18:49:25.607084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd816905a9506'
down_revision = '74245a210567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('month', sa.Integer() ))
    op.add_column('users', sa.Column('day', sa.Integer()))
    op.add_column('users', sa.Column('year', sa.Integer()))
    op.add_column('users', sa.Column('gender', sa.String()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'year')
    op.drop_column('users', 'day')
    op.drop_column('users', 'month')
    # ### end Alembic commands ###