"""added playlist model

Revision ID: 6b0daa9e0fdf
Revises: d816905a9506
Create Date: 2023-01-26 11:13:14.242486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0daa9e0fdf'
down_revision = 'd816905a9506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song_playlist',
    sa.Column('songId', sa.Integer(), nullable=False),
    sa.Column('playlistId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlistId'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['songId'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('songId', 'playlistId')
    )
    op.add_column('songs', sa.Column('description', sa.String(), nullable=True))
    op.add_column('songs', sa.Column('playlistId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'songs', 'playlists', ['playlistId'], ['id'])
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.drop_column('songs', 'playlistId')
    op.drop_column('songs', 'description')
    op.drop_table('song_playlist')
    op.drop_table('playlists')
    # ### end Alembic commands ###